name: build

on:
  push:
    branches: 
    - main
    paths-ignore:
    - README.md
    - .gitignore
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Cache setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"
    - name: "Cache references"
      uses: actions/cache@v2
      with:
        path: ${{ steps.cache-setup.outputs.path }}
        key: refcache-${{ steps.cache-setup.outputs.date }}
        restore-keys: |
          refcache-${{ steps.cache-setup.outputs.date }}
          refcache-
    - name: "Build drafts"
      uses: martinthomson/i-d-template@v1
